service: crud-with-sequealize
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  authors:
    handler: handler.getAuthors
    name: getAuthors
    events:
      - http:
          path: authors
          method: get
          cors: true
