service: crud-with-sequealize
frameworkVersion: '2'
useDotenv: true

plugins:
  - serverless-offline
  - serverless-sequelize-migrations

custom:
  migrationsPath: './database/migrations'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    DB_DIALECT: ${env:DB_DIALECT}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}

functions:
  authors:
    handler: handler.getAuthors
    name: getAuthors
    events:
      - http:
          path: authors
          method: get
          cors: true
