service: client

frameworkVersion: '2'

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  profile: jonnyalexbh
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'develop'}
  lambdaHashingVersion: 20201221

custom:
  stackPrefix: ${self:service}-sls-${self:provider.stage}

functions:
  - ${file(src/health_check/index.yml)}
  - ${file(src/clients/index.yml)}

resources:
  - ${file(resources/tables/clients.yml)}
