Resources: 
  ClientsTable: 
    Properties: 
      AttributeDefinitions: 
        - AttributeName: client_id
          AttributeType: S
      KeySchema: 
        - AttributeName: client_id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: ${file(resources/index.json):clients.tableName}
    Type: "AWS::DynamoDB::Table"
